version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoengine
    versions:
    - "> 0.21.0"
  - dependency-name: pylint
    versions:
    - 2.7.2
    - 2.7.4
  - dependency-name: astroid
    versions:
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: aniso8601
    versions:
    - 8.1.0
    - 8.1.1
    - 9.0.0
  - dependency-name: graphql-core
    versions:
    - 3.1.3
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
  - dependency-name: rx
    versions:
    - 3.1.1
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: chardet
    versions:
    - 4.0.0
  - dependency-name: parso
    versions:
    - 0.8.1
  - dependency-name: unidecode
    versions:
    - 1.1.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001211
  - dependency-name: css-loader
    versions:
    - 5.2.3
- package-ecosystem: npm
  directory: "/integration"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
