sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker-compose -f docker-compose.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin;
    docker-compose -f docker-compose.yml push;
    fi
