sudo: required

services:
  - docker

before_install:
  - docker-compose -f docker-compose.yml build

script:
  - true

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker-compose push;
    fi
