version: "3.4"
services:
  worker:
    networks:
      - outside
    deploy:
      update_config:
        order: start-first
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImFjODA3MmY5LTExYTktNDViMS1iOTUyLWQ5ZjIwNTk0NzJjOCIsImlhdCI6MTUxNDc0ODI3MSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4xMzEuMTYxLjE5MyIsIjE1OS44OS4xMzkuMzUiXSwidHlwZSI6ImNsaWVudCJ9XX0.S7sP9cDlLywqmpZpker7uZrLBY0xmDFzfXWxb30V1vAtCLrvCItcSUW8Yt3VLcoJu60vbf7_oe0fIiwok68oVw
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - DB_HOST=localhost
      - STAGE=production
  scheduler:
    networks:
      - outside
    deploy:
      update_config:
        order: start-first
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImFjODA3MmY5LTExYTktNDViMS1iOTUyLWQ5ZjIwNTk0NzJjOCIsImlhdCI6MTUxNDc0ODI3MSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4xMzEuMTYxLjE5MyIsIjE1OS44OS4xMzkuMzUiXSwidHlwZSI6ImNsaWVudCJ9XX0.S7sP9cDlLywqmpZpker7uZrLBY0xmDFzfXWxb30V1vAtCLrvCItcSUW8Yt3VLcoJu60vbf7_oe0fIiwok68oVw
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - DB_HOST=localhost
      - STAGE=production

  web:
    networks:
      - outside
    deploy:
      update_config:
        order: start-first
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImIwMGVkYTdmLThlMzktNDAxNS1hZDViLWNhYjUyNDdlMTY3OCIsImlhdCI6MTUyNzc4MDEwMSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE1OS44OS4xMzkuMzUiLCIxMDQuMTMxLjE2MS4xOTMiXSwidHlwZSI6ImNsaWVudCJ9XX0.EH386Oa7I2jfAoyKKXHF9Bt5AY2ZrC9wgYovc1OcfVBU7Hbe_7B7FoaWTeR-d_H6D_xxb39qOC1yxR8fNPrCmg
      - DB_HOST=localhost
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production

networks:
  outside:
    external:
      name: "host"
