version: '3'
services:
  scheduler:    
    restart: unless-stopped    
    network_mode: host
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjFiOTNkMTMyLTdkYzUtNDY1NS05YmZmLWMyYmM5M2YyMTJhMCIsImlhdCI6MTUxNDY4Mzk2Miwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4xMzEuMTYxLjE5MyIsIjE1OS44OS4xMjkuNzgiXSwidHlwZSI6ImNsaWVudCJ9XX0.HdHyPLiC_PTsFsf4bz9LJO6bxIfAtLQckvJuWwpyg17eJgeWeFHTg5RYvkspxB-kTewEqdHlPd7pizLRurQ13g
      - SENTRY_DSN=https://4ea62a4485a94a5ab1c93324e0e029a1:060a4c83525e4ffb8b00853c85e847cc@sentry.io/185882
      - DB_HOST=localhost

  web:
    restart: unless-stopped
    network_mode: host
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjFiOTNkMTMyLTdkYzUtNDY1NS05YmZmLWMyYmM5M2YyMTJhMCIsImlhdCI6MTUxNDY4Mzk2Miwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4xMzEuMTYxLjE5MyIsIjE1OS44OS4xMjkuNzgiXSwidHlwZSI6ImNsaWVudCJ9XX0.HdHyPLiC_PTsFsf4bz9LJO6bxIfAtLQckvJuWwpyg17eJgeWeFHTg5RYvkspxB-kTewEqdHlPd7pizLRurQ13g
      - SENTRY_DSN=https://4ea62a4485a94a5ab1c93324e0e029a1:060a4c83525e4ffb8b00853c85e847cc@sentry.io/185882
      - DB_HOST=localhost
    ports:
      - 80:80
      - 443:443
