version: "3.4"
services:
  redis:
    volumes:
      - /data/redis:/data
  mongo:
    volumes:
      - /data/mongo:/data/db
  worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImYxNTdmZjY5LWUzMWUtNDNmYy05MWNmLTk2OTFmZDA3ZTBhNCIsImlhdCI6MTU0ODI3NzQxNiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiXSwidHlwZSI6ImNsaWVudCJ9XX0.KMfkNIXlziDFZrQb8D1wRrTab0U-tl5CILM8I7ycLW9aP7rTA7KKk5PsqbcUei6QwITwsSVcVNB3yIz1UM9dQA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - WORKER_OFFSET={{.Task.Slot}}
    deploy:
      replicas: 2
  rq_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImYxNTdmZjY5LWUzMWUtNDNmYy05MWNmLTk2OTFmZDA3ZTBhNCIsImlhdCI6MTU0ODI3NzQxNiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiXSwidHlwZSI6ImNsaWVudCJ9XX0.KMfkNIXlziDFZrQb8D1wRrTab0U-tl5CILM8I7ycLW9aP7rTA7KKk5PsqbcUei6QwITwsSVcVNB3yIz1UM9dQA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
  cron:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImM3MGFlMjE1LTk1MzUtNGJhNy05ZWZiLWM5MWY3MmQyMDY4NSIsImlhdCI6MTU0ODI3NzM5NSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiXSwidHlwZSI6ImNsaWVudCJ9XX0.YtBsFBEdfel02s-WsOiuv19LhwO3ZuGqxj5aDOBoZMtKoJuqjcP3W_xzbijy_ULcjfnGKRwW_1ICq-PR8OQpFQ
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
    deploy:
      update_config:
        order: start-first
    volumes:
      - /data/caddy:/root/.caddy
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQ3NzEwNTk5LTdjOTEtNGM2Ni04MTkxLTdmMTg5OWQyZjBjYiIsImlhdCI6MTU0ODI3NzM3MSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiXSwidHlwZSI6ImNsaWVudCJ9XX0.n9iKmZiT98kjzz89v8uozDPZXMySyOXP9xNACu76qfxFDabMxml-A4KVdCmnH38rHuF08yvtnx8p6y96mdNRhQ
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - DO_AUTH_TOKEN
    ports:
      - 80:80
      - 443:443
