version: "3.4"
services:
  influx:
    volumes:
      - /data/influx:/var/lib/influxdb
  redis:
    volumes:
      - /data/redis:/data
  mongo:
    volumes:
      - /data/mongo:/data/db
    deploy:
      resources:
        limits:
          memory: 2000m
  grafana:
    volumes:
      - /data/grafana:/var/lib/grafana
  worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjZkMTc1NjM4LTdjYzktNGMyNi04OWFlLTUwZWY4N2M3MDY1NCIsImlhdCI6MTU0ODcxNDYwNiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY4LjE4My4xNjQuMjQwIiwiMTA0LjI0OC43OC44MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.RDVq9kFX-xXCd2Bc0f3LK4At81hmYELQfL8G-BGk8VP2ALw2sXQYHUsTKXHqKHYqH789atl2dEai3O-rfUEu-A
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - WORKER_OFFSET={{.Task.Slot}}
    deploy:
      replicas: 2
  rq_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4NmNiZjkxLTkwZWMtNDJmMC04YTY2LWUxZjEzYzUwZDg4MiIsImlhdCI6MTU0ODcxNDcyNCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Iswu6xnxOjgkFkWiyWc9qQwLtZ0sREDylzIJHJRvRjSFb_yGNbX6HeeCrdrwfNnp9dPja1SVPJuhN8-SWXWMbA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
  cron:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijg0Nzg1MmYwLTNmNjctNDBkZS1iZWVmLWJkMjM4NjY0ZTlmOSIsImlhdCI6MTU0ODcxNDc1OCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.MKhr-j--B95Z6lBpQqlLILtWUZSs6GjJdbh-BXK-xJvAaGLRrhP_Ldz6MN7OwzNrjoajVVrgtL881kcPhlA_pA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
    volumes:
      - /data/caddy:/root/.caddy
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM0ZjQ0N2YwLTFhMjctNGY1Yy1iZmJmLTAzNmU3ZTUwNGNhMSIsImlhdCI6MTU0ODcxNDgxMiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.sJTwjukALofUQMI5fXISE0pkYK1rVeGrJPEPhr9QJcRLcz8oVMT0svdHkkqg8YiLtRZo7n-Nz4skd-9HIfSfeQ
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - DO_AUTH_TOKEN
    ports:
      - 80:80
      - 443:443
