version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  clashstats:
    build: .
    restart: unless-stopped
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjFjZWQxNDkwLTA2MTAtNDBjMi1hMjhmLTA5OWIwYjk5YjZkNSIsImlhdCI6MTQ4NjE3MTA2OSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEzOC4xOTcuMzUuMTUxIl0sInR5cGUiOiJjbGllbnQifV19.3VuCFumJ-gCn8896tFXSd8Yk7dTyPnp1QY75UP2yjvjG0-Kciqlvsj7ZunXz6z1Ez5UEGlnZUmjtIa3SF5s1Cw
      - VIRTUAL_HOST=clashstats.download
