version: "3.4"
services:
  mongo:
    image: mongo:4.4.1-bionic
  redis:
    image: redis:5.0.4-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
    depends_on:
      - mongo
      - redis
      - rq_player_worker
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
      - mongo
      - imgproxy-cache
  imgproxy:
    image: darthsim/imgproxy:v2.13
    environment:
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_MAX_CLIENTS=100
      - IMGPROXY_DOWNLOAD_TIMEOUT=10
      - IMGPROXY_TTL=31622400
  imgproxy-cache:
    image: "amir20/imgproxy-cache:${TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile.imgproxy
    depends_on:
      - imgproxy
  rq_player_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker player player_request"
    depends_on:
      - redis
      - mongo
  rq_calculation_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker calculation"
    depends_on:
      - redis
      - mongo
