version: '2'
services:
  proxy:    
    build: ./proxy
    restart: unless-stopped
    image: zzrot/alpine-caddy
    ports:
        - 80:80
        - 443:443
    volumes:
        - /root/.caddy
                
    depends_on:
        - clashstats  

  clashstats:
    build: .
    restart: unless-stopped
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQ0NWNhYmY3LWZiMTctNDZmYS05NzY4LTM0ZTU0ZWRkOTY5YSIsImlhdCI6MTQ5MDk4OTc2MSwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjQ1Ljc2LjI2LjE4OSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.T5nWDrLq6nW_F011H2RNOGuLzR4hlvtSFGITHDhxLPbsG9m15iumXy4zLpHAcrCXzlPrOeLkaTmCBORMZnZ4AA
      - VIRTUAL_HOST=clashstats.download
