version: "3.4"
services:
  redis:
    image: redis:5-alpine
  scheduler:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "scheduler"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
  player_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "player_worker"
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - db
      - redis
