version: "3.4"
services:
  mongo:
    image: mongo:4.1
  influx:
    image: influxdb:1.7-alpine
  grafana:
    image: grafana/grafana
    depends_on:
      - influx
    ports:
      - 3000:3000
  redis:
    image: redis:5-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
    depends_on:
      - mongo
      - redis
      - influx
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
      - mongo
      - influx
  rq_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker player calculation"
    depends_on:
      - redis
      - mongo
      - influx
