version: "3.4"
services:
  redis:
    volumes:
      - /data/redis:/data
  mongo:
    volumes:
      - /data/mongo:/data/db
    deploy:
      resources:
        limits:
          memory: 2000m
  worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjZkMTc1NjM4LTdjYzktNGMyNi04OWFlLTUwZWY4N2M3MDY1NCIsImlhdCI6MTU0ODcxNDYwNiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY4LjE4My4xNjQuMjQwIiwiMTA0LjI0OC43OC44MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.RDVq9kFX-xXCd2Bc0f3LK4At81hmYELQfL8G-BGk8VP2ALw2sXQYHUsTKXHqKHYqH789atl2dEai3O-rfUEu-A
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - WORKER_OFFSET={{.Task.Slot}}
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200m
  rq_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4NmNiZjkxLTkwZWMtNDJmMC04YTY2LWUxZjEzYzUwZDg4MiIsImlhdCI6MTU0ODcxNDcyNCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Iswu6xnxOjgkFkWiyWc9qQwLtZ0sREDylzIJHJRvRjSFb_yGNbX6HeeCrdrwfNnp9dPja1SVPJuhN8-SWXWMbA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
  cron:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijg0Nzg1MmYwLTNmNjctNDBkZS1iZWVmLWJkMjM4NjY0ZTlmOSIsImlhdCI6MTU0ODcxNDc1OCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.MKhr-j--B95Z6lBpQqlLILtWUZSs6GjJdbh-BXK-xJvAaGLRrhP_Ldz6MN7OwzNrjoajVVrgtL881kcPhlA_pA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
  imgproxy-cache:
    deploy:
      labels:
        - traefik.frontend.rule=Host:i.clashleaders.com
        - traefik.enable=true
        - traefik.port=2015
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.SSLRedirect=true
    networks:
      - web
      - default
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
    volumes:
      - /data/caddy:/root/.caddy
    deploy:
      resources:
        limits:
          memory: 400m
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM0ZjQ0N2YwLTFhMjctNGY1Yy1iZmJmLTAzNmU3ZTUwNGNhMSIsImlhdCI6MTU0ODcxNDgxMiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.sJTwjukALofUQMI5fXISE0pkYK1rVeGrJPEPhr9QJcRLcz8oVMT0svdHkkqg8YiLtRZo7n-Nz4skd-9HIfSfeQ
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - DO_AUTH_TOKEN
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
    ports:
      - 80:80
      - 443:443

networks:
  web:
    external: true
