version: "3.4"
services:
  redis:
    volumes:
      - /data/redis:/data
  mongo:
    volumes:
      - /data/mongo:/data/db
  worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijc4MDhhYzU5LTJhYjAtNGUyNS05MDlmLWQ1YmY1NjhiMDM4OCIsImlhdCI6MTU5MDg5MTg5NCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kebKZ_0SWGEZiq6KZ_spj-NtE8bd_1_7Eo8hIXFQQr23rH6w1zeimb5UQwOSsBhkFb5EziYkrL_Xe0OMg8t4qA,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImYzNDRjODYxLTY0ZTAtNDJkOC1hY2Q0LTdkZTg3ZjFiMzc4NSIsImlhdCI6MTYyODI4NTMzMywic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kHOi_crxpHx4RlxPmMHOVUvzasJTQlw2WFU_AgMAwh0sosEdCfCScvsJNgfYXPKEhJ31WiNcK04fvwMoI2ae6Q
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - WORKER_OFFSET={{.Task.Slot}}
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 400m
  rq_calculation_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQxM2I5NDE1LWQ1MmEtNGM2YS1iZTUyLTlkM2I2NjVkOWI4ZSIsImlhdCI6MTU5MTA0OTgyNywic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kHV83-93nISFrd_J1nltu7WK4HqgY0-VtyX8Y6tBFOyUASXPLVDtvlzCXmGTmuSr0ZT_VJYjerWM2N4dTUDLGg
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
    deploy:
      resources:
        limits:
          memory: 200m
  rq_war_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQxM2I5NDE1LWQ1MmEtNGM2YS1iZTUyLTlkM2I2NjVkOWI4ZSIsImlhdCI6MTU5MTA0OTgyNywic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kHV83-93nISFrd_J1nltu7WK4HqgY0-VtyX8Y6tBFOyUASXPLVDtvlzCXmGTmuSr0ZT_VJYjerWM2N4dTUDLGg
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400m
  cron:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijc4MDhhYzU5LTJhYjAtNGUyNS05MDlmLWQ1YmY1NjhiMDM4OCIsImlhdCI6MTU5MDg5MTg5NCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kebKZ_0SWGEZiq6KZ_spj-NtE8bd_1_7Eo8hIXFQQr23rH6w1zeimb5UQwOSsBhkFb5EziYkrL_Xe0OMg8t4qA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
  imgproxy:
    environment:
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
  imgproxy-cache:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.imgproxy.rule=Host(`i.clashleaders.com`)
        - traefik.http.routers.imgproxy.tls.certresolver=myresolver
        - traefik.http.routers.imgproxy.middlewares=i_headers
        - traefik.http.services.imgproxy.loadbalancer.server.port=2015
        - traefik.http.middlewares.i_headers.headers.browserXssFilter=true
        - traefik.http.middlewares.i_headers.headers.contentTypeNosniff=true
        - traefik.http.middlewares.i_headers.headers.forceSTSHeader=true
        - traefik.http.middlewares.i_headers.headers.stsSeconds=315360000
        - traefik.http.middlewares.i_headers.headers.sslredirect=true
        - traefik.http.middlewares.i_headers.headers.sslForceHost=true
    networks:
      - web
      - default
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
    volumes:
      - /data/caddy:/root/.caddy
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 700m
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.nowww.rule=Host(`clashleaders.com`)
        - traefik.http.routers.nowww.entrypoints=web
        - traefik.http.routers.nowww.middlewares=web_headers

        - traefik.http.routers.web.rule=Host(`www.clashleaders.com`)
        - traefik.http.routers.web.entrypoints=web
        - traefik.http.routers.web.middlewares=web_headers

        - traefik.http.routers.websecured.rule=Host(`www.clashleaders.com`)
        - traefik.http.routers.websecured.entrypoints=websecure
        - traefik.http.routers.websecured.tls.certresolver=myresolver
        - traefik.http.routers.websecured.middlewares=web_headers

        - traefik.http.services.websecured.loadbalancer.server.port=80

        - traefik.http.middlewares.web_headers.headers.browserXssFilter=true
        - traefik.http.middlewares.web_headers.headers.contentTypeNosniff=true
        - traefik.http.middlewares.web_headers.headers.frameDeny=true
        - traefik.http.middlewares.web_headers.headers.forceSTSHeader=true
        - traefik.http.middlewares.web_headers.headers.stsSeconds=315360000
        - traefik.http.middlewares.web_headers.headers.sslredirect=true
        - traefik.http.middlewares.web_headers.headers.sslForceHost=true
        - traefik.http.middlewares.web_headers.headers.sslHost=www.clashleaders.com
        - traefik.http.middlewares.web_headers.headers.stsPreload=true
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM0YTY4NjFlLTE4YmMtNGY0Yy1hZDczLTJiYzNlYTQ1ZjU0YSIsImlhdCI6MTU5MTA0OTg3Miwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.3HQ9H_ZyOzrtRIBEMmT_XaF5mCNDtfJQZiZ47kEXn_cio2WotWKgUk-p-j_o-Ww1bxmZkGIb2pyPaRf_IH93hg
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
    networks:
      - web
      - default

networks:
  web:
    external: true
