version: '3'
services:
  scheduler:
    hostname: scheduler
    image: amir20/clashstats-scheduler:latest
    build:
      context: .
      dockerfile: Dockerfile.scheduler           

  web:
    build: .
    image: amir20/clashstats-web:latest
    hostname: web    