version: "3.4"
services:
  mongo:
    image: mongo:4.1.9
  redis:
    image: redis:5.0.4-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
    depends_on:
      - mongo
      - redis
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
      - mongo
      - imgproxy-cache
  imgproxy:
    image: darthsim/imgproxy:v2.2.12
    environment:
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_MAX_CLIENTS=100
      - IMGPROXY_DOWNLOAD_TIMEOUT=10
      - IMGPROXY_TTL=2628000
  imgproxy-cache:
    image: "amir20/imgproxy-cache:${TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile.imgproxy
    depends_on:
      - imgproxy
  rq_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker player calculation player_request"
    depends_on:
      - redis
      - mongo
