version: "3.4"
services:
  redis:
    image: redis:5-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
  rq_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker player calculation"
    depends_on:
      - redis
