version: "3.2"
services:
  scheduler:
    image: amir20/clashleaders:latest
    hostname: scheduler
    command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-scheduler.conf"

  worker:
    image: amir20/clashleaders:latest
    hostname: worker
    command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-worker.conf"

  web:
    build: .
    image: amir20/clashleaders:latest
    hostname: web
