version: "3.4"
services:
  redis:
    volumes:
      - /data/redis:/data
  mongo:
    volumes:
      - /data/mongo:/data/db
      - /data/backups:/data/backups
    deploy:
      resources:
        limits:
          memory: 2000m
  worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijc4MDhhYzU5LTJhYjAtNGUyNS05MDlmLWQ1YmY1NjhiMDM4OCIsImlhdCI6MTU5MDg5MTg5NCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY0LjIyNy4xMDIuMzEiXSwidHlwZSI6ImNsaWVudCJ9XX0.kebKZ_0SWGEZiq6KZ_spj-NtE8bd_1_7Eo8hIXFQQr23rH6w1zeimb5UQwOSsBhkFb5EziYkrL_Xe0OMg8t4qA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - WORKER_OFFSET=1
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200m
  rq_calculation_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4NmNiZjkxLTkwZWMtNDJmMC04YTY2LWUxZjEzYzUwZDg4MiIsImlhdCI6MTU0ODcxNDcyNCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Iswu6xnxOjgkFkWiyWc9qQwLtZ0sREDylzIJHJRvRjSFb_yGNbX6HeeCrdrwfNnp9dPja1SVPJuhN8-SWXWMbA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
    deploy:
      resources:
        limits:
          memory: 200m
  rq_player_worker:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4NmNiZjkxLTkwZWMtNDJmMC04YTY2LWUxZjEzYzUwZDg4MiIsImlhdCI6MTU0ODcxNDcyNCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Iswu6xnxOjgkFkWiyWc9qQwLtZ0sREDylzIJHJRvRjSFb_yGNbX6HeeCrdrwfNnp9dPja1SVPJuhN8-SWXWMbA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200m
  cron:
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijg0Nzg1MmYwLTNmNjctNDBkZS1iZWVmLWJkMjM4NjY0ZTlmOSIsImlhdCI6MTU0ODcxNDc1OCwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.MKhr-j--B95Z6lBpQqlLILtWUZSs6GjJdbh-BXK-xJvAaGLRrhP_Ldz6MN7OwzNrjoajVVrgtL881kcPhlA_pA
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
  imgproxy:
    image: darthsim/imgproxy:v2.2.12
    environment:
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
  imgproxy-cache:
    deploy:
      labels:
        - traefik.frontend.rule=Host:i.clashleaders.com
        - traefik.enable=true
        - traefik.port=2015
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.frameDeny=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.SSLRedirect=true
    networks:
      - web
      - default
  web:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
    volumes:
      - /data/caddy:/root/.caddy
    deploy:
      resources:
        limits:
          memory: 400m
    environment:
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM0ZjQ0N2YwLTFhMjctNGY1Yy1iZmJmLTAzNmU3ZTUwNGNhMSIsImlhdCI6MTU0ODcxNDgxMiwic3ViIjoiZGV2ZWxvcGVyL2EzZjUxMmFlLTVmZWQtM2Q0MC00Y2E3LTdhYzc0ZTQ0YjQyOCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwNC4yNDguNzguODAiLCI2OC4xODMuMTY0LjI0MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.sJTwjukALofUQMI5fXISE0pkYK1rVeGrJPEPhr9QJcRLcz8oVMT0svdHkkqg8YiLtRZo7n-Nz4skd-9HIfSfeQ
      - BUGSNAG_API_KEY=cdb173414b6d879639165cedcc730d73
      - STAGE=production
      - IMGPROXY_KEY=15c1f2542afea936263aaf8a5244e0f2edf7bfb54dec26fb19b12133ad02869b254d71587227d3a58e43fb6885f1290cb158ab31e62d4f6361c50f21e089883a
      - IMGPROXY_SALT=95490c60f0bba290a0ae56e897ad5a9a7845ca375ca9922d07bbfacb62453c05165048c75fb3488018f34115c98ec2fb7a1c7e1a4508cd20233ad9b2190986e5
      - IMGPROXY_BASE=https://i.clashleaders.com/
    deploy:
      labels:
        - traefik.enable=true
        - traefik.www.frontend.rule=Host:www.clashleaders.com
        - traefik.www.port=2015
        - traefik.www.frontend.headers.browserXSSFilter=true
        - traefik.www.frontend.headers.contentTypeNosniff=true
        - traefik.www.frontend.headers.frameDeny=true
        - traefik.www.frontend.headers.forceSTSHeader=true
        - traefik.www.frontend.headers.STSSeconds=315360000
        - traefik.www.frontend.headers.SSLRedirect=true
        - traefik.www.frontend.headers.SSLForceHost=true
        - traefik.www.frontend.headers.SSLHost=www.clashleaders.com
        - traefik.top.frontend.rule=Host:clashleaders.com
        - traefik.top.port=2015
        - traefik.top.frontend.headers.browserXSSFilter=true
        - traefik.top.frontend.headers.contentTypeNosniff=true
        - traefik.top.frontend.headers.frameDeny=true
        - traefik.top.frontend.headers.forceSTSHeader=true
        - traefik.top.frontend.headers.STSSeconds=315360000
        - traefik.top.frontend.headers.SSLRedirect=true
        - traefik.top.frontend.headers.SSLForceHost=true
        - traefik.top.frontend.headers.SSLHost=www.clashleaders.com
        - traefik.top.frontend.headers.STSPreload=true
        - traefik.top.frontend.headers.STSIncludeSubdotops=true
    networks:
      - web
      - default

networks:
  web:
    external: true
