version: "3.4"
services:
  mongo:
    image: mongo:4.1.9
  redis:
    image: redis:5.0.4-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
    depends_on:
      - mongo
      - redis
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
      - mongo
  rq_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker player calculation player_request"
    depends_on:
      - redis
      - mongo
