version: "3.4"
services:
  mongo:
    image: mongo:5.0.2
    command: --wiredTigerCacheSizeGB=0.25
  redis:
    image: redis:6-alpine
  cron:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "cron.sh"
  worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "worker"
    depends_on:
      - mongo
      - redis
  web:
    build: .
    image: "amir20/clashleaders:${TAG:-latest}"
    depends_on:
      - redis
      - mongo
      - imgproxy-cache
      - rq_calculation_worker
  imgproxy:
    image: darthsim/imgproxy:v2.17
    environment:
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_MAX_CLIENTS=100
      - IMGPROXY_DOWNLOAD_TIMEOUT=10
      - IMGPROXY_TTL=31622400
  imgproxy-cache:
    image: "amir20/imgproxy-cache:${TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile.imgproxy
    depends_on:
      - imgproxy
  rq_calculation_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker calculation"
    depends_on:
      - redis
      - mongo
  rq_war_worker:
    image: "amir20/clashleaders:${TAG:-latest}"
    command: "rq_worker war"
    environment:
      - USE_SCHEDULER=true
    depends_on:
      - redis
      - mongo
