version: '3.2'
services:
  scheduler:
    image: amir20/clashleaders:latest
    hostname: scheduler
    command: '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-scheduler.conf'

  web:
    build:
      context: .
      cache_from:
        - amir20/clashleaders:latest
    image: amir20/clashleaders:latest
    hostname: web