[tool.poetry]
name = "clashleaders"
version = "0.1.0"
description = ""
authors = ["Amir Raminfar <findamir@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.3"
awesome-slugify = "^1.6.5"
bugsnag = "^4.3.0"
CairoSVG = "^2.5.2"
Flask = "^2.2.2"
Flask-Caching = "^2.0.1"
Flask-GraphQL = "^2.0.1"
Flask-WTF = "^1.0.1"
graphene = "2.1.9"
numpy = "^1.23.4"
pandas = "^1.5.1"
pymongo = "^4.3.2"
mongoengine = "^0.24.2"
redis = "^4.4.4"
rq = "^1.11.1"
rq-dashboard = "^0.6.1"
scikit-learn = "^1.1.3"
scipy = "^1.9.3"
uvloop = "^0.17.0"
XlsxWriter = "^3.0.3"
gunicorn = "^20.1.0"
blinker = "^1.5"
markdown = "^3.4.1"
requests = "^2.28.1"
cachetools = "^5.2.0"
inflection = "^0.5.1"
protobuf = "^4.21.9"
contentful = "^1.13.1"


[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
mypy = "^0.991"
pytest = "^7.2.0"
snapshottest = "^0.6.0"
aioresponses = "^0.7.3"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
worker = "clashleaders.worker:main"
rq_worker = "clashleaders.rq_worker:main"
update_all = "clashleaders.cli:update_all_calculations"
update_status = "clashleaders.model:Status.update_status"
delete_outdated = "clashleaders.batch.purge:delete_outdated"
reset_stats = "clashleaders.batch.purge:reset_stats"
compute_similar_clans = "clashleaders.batch.similar_clan:compute_similar_clans"
update_troops = "clashleaders.model:AverageTroop.update_all"
fetch_clan_leaderboards = "clashleaders.cli:fetch_clan_leaderboards"
fetch_tags = "clashleaders.cli:fetch_tags"
