[tool.poetry]
name = "clashleaders"
version = "0.1.0"
description = ""
authors = ["Amir Raminfar <findamir@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11"
aiohttp = "^3.8.5"
awesome-slugify = "^1.6.5"
bugsnag = "^4.5.0"
CairoSVG = "^2.7.1"
Flask = "^2.3.2"
Flask-Caching = "^2.0.2"
Flask-WTF = "^1.1.1"
graphene = "^3.2.2"
numpy = "^1.25.2"
pandas = "^2.0.3"
pymongo = "^4.4.1"
mongoengine = "^0.27.0"
redis = "^4.6.0"
rq = "^1.15.1"
rq-dashboard = "^0.6.1"
scikit-learn = "^1.3.0"
scipy = "^1.11.1"
uvloop = "^0.17.0"
XlsxWriter = "^3.1.2"
gunicorn = "^21.2.0"
blinker = "^1.6.2"
markdown = "^3.4.4"
requests = "^2.31.0"
cachetools = "^5.3.1"
inflection = "^0.5.1"
protobuf = "^4.23.4"
contentful = "^2.0.0"
cachelib = "^0.10.2"
setuptools = "^67.8.0"
pillow = "^9.5.0"
multidict = "^6.0.4"
graphql-server = {extras = ["flask"], version = "^3.0.0b6"}


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.4.1"
pytest = "^7.4.0"
snapshottest = "^0.6.0"
aioresponses = "^0.7.4"
pytest-mock = "^3.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
worker = "clashleaders.worker:main"
rq_worker = "clashleaders.rq_worker:main"
update_all = "clashleaders.cli:update_all_calculations"
update_status = "clashleaders.model:Status.update_status"
delete_outdated = "clashleaders.batch.purge:delete_outdated"
reset_stats = "clashleaders.batch.purge:reset_stats"
compute_similar_clans = "clashleaders.batch.similar_clan:compute_similar_clans"
update_troops = "clashleaders.model:AverageTroop.update_all"
fetch_clan_leaderboards = "clashleaders.cli:fetch_clan_leaderboards"
fetch_tags = "clashleaders.cli:fetch_tags"
