import clashleaders.views.badge
import clashleaders.views.clan
import clashleaders.views.country
import clashleaders.views.error
import clashleaders.views.index
import clashleaders.views.similar_clans
import clashleaders.views.sitemap
import clashleaders.views.static
import clashleaders.views.status
import clashleaders.views.verified
import clashleaders.views.clan_player
