version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip make jq git-lfs
            pip install --upgrade pip
            pip install 'docker-compose==1.23.0'
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            make build
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Run int tests
          command: |
            make int
