version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache \
              py-pip \
              make
            pip install \
              docker-compose
      - run:
          name: Build application Docker image
          command: |
            make build
    python_test:
      docker:
        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run:
            name: Install build dependencies
            command: |
              apk add --no-cache \
                py-pip \
                make
        - run:
            name: Install dependencies
            command: |
              make init
        - run:
            name: Run tests
            command: |
              make test
    assets_build:
      docker:
        - image: circleci/node:10.11.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              node install
        - run:
            name: Build assets
            command: |
              node run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - python_test
      - assets_build
