version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip make jq git-lfs
            pip install --upgrade pip
            pip install 'docker-compose==1.23.0'
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Build application Docker image
          command: |
            make build
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" --filter=reference="amir20/*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/docker-layers.tar
      - run:
          name: Run int tests
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d mongo
            docker cp mongosnapshot/clashleaders.gz $(docker-compose -f docker-compose.yml -f docker-compose.test.yml ps -q mongo):/tmp
            docker-compose -f docker-compose.yml -f docker-compose.test.yml exec mongo mongorestore --gzip --archive=/tmp/clashleaders.gz
            make int
