"""empty message

Revision ID: 0fefde32f73a
Revises: 2dc765a0390d
Create Date: 2019-01-06 04:34:13.474065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fefde32f73a'
down_revision = '2dc765a0390d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clan_created_on'), 'clan', ['created_on'], unique=False)
    op.create_index(op.f('ix_player_clan_id'), 'player', ['clan_id'], unique=False)
    op.create_index(op.f('ix_player_created_on'), 'player', ['created_on'], unique=False)
    op.drop_column('player', 'legendStatistics')
    op.drop_column('player', 'achievements')
    op.drop_column('player', 'donations')
    op.drop_column('player', 'attackWins')
    op.drop_column('player', 'troops')
    op.drop_column('player', 'bestTrophies')
    op.drop_column('player', 'expLevel')
    op.drop_column('player', 'townHallWeaponLevel')
    op.drop_column('player', 'warStars')
    op.drop_column('player', 'defenseWins')
    op.drop_column('player', 'bestVersusTrophies')
    op.drop_column('player', 'versusTrophies')
    op.drop_column('player', 'spells')
    op.drop_column('player', 'versusBattleWinCount')
    op.drop_column('player', 'versusBattleWins')
    op.drop_column('player', 'townHallLevel')
    op.drop_column('player', 'donationsReceived')
    op.drop_column('player', 'role')
    op.drop_column('player', 'heroes')
    op.drop_column('player', 'league')
    op.drop_column('player', 'trophies')
    op.drop_column('player', 'builderHallLevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('builderHallLevel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('trophies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('league', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('heroes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('donationsReceived', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('townHallLevel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('versusBattleWins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('versusBattleWinCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('spells', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('versusTrophies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('bestVersusTrophies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('defenseWins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('warStars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('townHallWeaponLevel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('expLevel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('bestTrophies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('troops', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('attackWins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('donations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('achievements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('legendStatistics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_player_created_on'), table_name='player')
    op.drop_index(op.f('ix_player_clan_id'), table_name='player')
    op.drop_index(op.f('ix_clan_created_on'), table_name='clan')
    # ### end Alembic commands ###
