"""empty message

Revision ID: 2dc765a0390d
Revises: 31afd2859504
Create Date: 2019-01-06 02:46:23.696509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dc765a0390d'
down_revision = '31afd2859504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('bytes', postgresql.BYTEA(), nullable=True))
    op.drop_column('player', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('player', 'bytes')
    # ### end Alembic commands ###
