"""empty message

Revision ID: 8e79948e21ac
Revises: 
Create Date: 2019-01-04 01:07:39.140323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e79948e21ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('versusPoints', sa.Integer(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_tag'), 'clan', ['tag'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_tag'), 'player', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_tag'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_clan_tag'), table_name='clan')
    op.drop_table('clan')
    # ### end Alembic commands ###
