on:
  pull_request:
    branches:
      - master
name: Test
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Build Docker images
        run: make build
      - name: Run tests
        run: make test
      - name: Run integration tests
        run: make int
  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
