on:
  push:
    branches:
      - master
name: Test
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Build Docker images
        run: make build
      - name: Run tests
        run: make test
      - name: Run integration tests
        run: make int
