on: push
name: Test
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        run: make build
      - name: make test
        run: make test
      - name: make int
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d mongo
          docker cp mongosnapshot/clashleaders.gz $(docker-compose -f docker-compose.yml -f docker-compose.test.yml ps -q mongo):/tmp
          docker-compose -f docker-compose.yml -f docker-compose.test.yml exec mongo mongorestore --gzip --archive=/tmp/clashleaders.gz
          make int
