on: push
name: Test
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        run: make build
      - name: make test
        run: make test
      - name: make int
        run: |
          make int
